name: Discord Commit Notifier

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commits to Discord
        run: |
          COMMITS=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[] | "- \(.message)"')

          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"@everyone  **New Push by ${{ github.actor }}**\\n\\n **Commits:**\\n$COMMITS\\n\\n━━━━━━━━━━━━━━\\n **DEV REMINDER**\\n• git pull before opening the project\\n• git add .\\n• git commit -m \\\"message\\\"\\n• git push\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
